services:

  app:
    build: .
    container_name: bot
    env_file:
      - ./src/.env
    ports:
      - 8000:8000


  redis:

      container_name: redis
      image: redis:latest
      hostname: redis
      expose:
        - 6379
      restart: unless-stopped
      volumes:
        - redis: /var/lib/redis

  postgres:

      container_name: postgres
      image: postgres:latest
      hostname: postgres
      ports:
        - 5432:5432
      restart: unless-stopped
      env_file:
        - ./src/.env
      environment:
        POSTGRES_USER=POSTGRES_USER

      volumes:
        - postgresql: /var/lib/postgresql/data



volumes:
  postgresql:
  redis: